#!/bin/sh
#
# lxc Start/Stop LXC autoboot containers
#
# chkconfig: 345 99 01
# description: Starts/Stops all LXC containers configured for autostart.
#
### BEGIN INIT INFO
# Provides: lxc
# Required-Start: $syslog $remote_fs
# Required-Stop: $syslog $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Bring up/down LXC autostart containers
# Description: Bring up/down LXC autostart containers
### END INIT INFO

# To be replaced by LSB functions, if they can be found
# Defined here for distributions that don't have log_daemon_msg
log_daemon_msg () {
    echo $@
}

# Try to source LSB init functions to define LSB log_* functions.
test ! -r /lib/lsb/init-functions ||
        . /lib/lsb/init-functions

# MOS Custom: Use mos-start script
start() {
#    # Setup host /dev for autodev containers.
    log_daemon_msg "Starting LXC" "lxc"
#    /usr/libexec/lxc/lxc-containers start
}

stop() {
    log_daemon_msg "Stopping LXC" "lxc"
    /usr/libexec/lxc/lxc-containers stop
}

# MOS Custom
mos_start() {
  LXC_DIRECTORY=$(jq -r '.directory' /boot/config/lxc.json)
  if [ ! -z "$LXC_DIRECTORY" ]; then
    # Safety check if pool where LXC is on is mounted
    if ! findmnt $(echo $LXC_DIRECTORY | cut -d '/' -f 1-3) >/dev/null 2>&1 ; then
      log_end_msg 1
      exit 1
    fi
    if [ ! -d /var/lib/lxc ] ; then
      mkdir -p /var/lib/lxc
    fi
    if [ ! -d $LXC_DIRECTORY ] ; then
      mkdir -p $LXC_DIRECTORY
    fi
  fi
  if ! findmnt /var/lib/lxc >/dev/null 2>&1 ; then
    mount --bind $LXC_DIRECTORY /var/lib/lxc
  fi
  if [ -f /etc/lxc/default.conf ] ; then
    rm -f /etc/lxc/default.conf
  fi
  ln -s /boot/config/system/lxc/default.conf /etc/lxc/default.conf

  if [ ! -d /var/www/lxc_icons ] ; then
    mkdir -p /var/www/lxc_icons
  fi
  if [ ! -d /var/www/lxc_custom ] ; then
    mkdir -p /var/www/lxc_custom
  fi
  if [ ! -d $LXC_DIRECTORY/custom_icons ] ; then
    mkdir -p $LXC_DIRECTORY/custom_icons
  fi
  mount --bind /var/lib/lxc_icons /var/www/lxc_icons 2>/dev/null
  mount --bind $LXC_DIRECTORY/custom_icons /var/www/lxc_custom 2>/dev/null
  chmod -R 755 /var/lib/lxc_icons $LXC_DIRECTORY/custom_icons
}

# MOS custom
mos_stop() {
  umount -f /var/lib/lxc 2>/dev/null
  umount -f /var/www/lxc_icons 2>/dev/null
  umount -f /var/www/lxc_custom 2>/dev/null
}

# See how we were called.
case "$1" in
    start)
        # MOS custom
        mos_start
        start
        log_end_msg $?
    ;;

    stop)
        stop
        log_end_msg $?
        # MOS custom
        mos_stop
    ;;

    restart|reload|force-reload)
        $0 stop
        $0 mos_stop
        sleep 1
        $0 mos_start
        $0 start
    ;;

    *)
        echo "Usage: $0 {start|stop|restart|reload|force-reload}"
        exit 2
    ;;
esac

exit $?
